### ISSUE TITLE
How can I choose the correct loss function for a specific task?

### ISSUE THREAD

**Issue by Yuxing-Wang-THU** [zswang666/softzoo#3]
Hi! In SoftZoo, there are FinalStepCoMLoss, TrajectoryFollowingLoss, PerStepCoVLoss, AnimatedEMDLoss, VelocityFollowingLoss, WaypointFollowingLoss, RotationLoss, ThrowingObjectLoss and ObjectVelocityLoss to be selected for a specific task. I don't know how to choose a correct loss. Can you provide some descriptions of these loss functions?
Thx!

**Comment by Yuxing-Wang-THU** [comment]
What is the meaning of "actuator_v" and"particle_v"? thx

**Comment by zswang666** [comment]
FinalStepCoMLoss: compute the loss based on the weighted sum of the average position at the last/final step.
PerStepCoVLoss: compute the loss based on the weighted sum of the average velocity at every step.
TrajectoryFollowingLoss: compute the loss based on the distance of the average position at every step as opposed to a desired trajectory.
VelocityFollowingLoss: compute the loss to encourage tracking a target velocity.
WaypointFollowingLoss: compute the loss to encourage tracking a target waypoint.
AnimatedEMDLoss: compute the loss to track a sequence of moving point clouds with earth moving distance (EMD).
RotationLoss: compute the loss to encourage rotation along a desired axis.
ThrowingObjectLoss: compute the loss based on the average position of an object with respect to its starting position at the final step.
ObjectVelocityLoss: compute the loss based on the average velocity of an object at every step.

Please check more detailed implement in [./algorithms/diffsim/loss.py](https://github.com/zswang666/softzoo/blob/main/algorithms/diffsim/loss.py)

actuator_v: velocity defined on actuators (muscle groups), where each actuator involves many particles in MPM.
particle_v: velocity defined on MPM particles

**Comment by Yuxing-Wang-THU** [comment]
> FinalStepCoMLoss: compute the loss based on the weighted sum of the average position at the last/final step. PerStepCoVLoss: compute the loss based on the weighted sum of the average velocity at every step. TrajectoryFollowingLoss: compute the loss based on the distance of the average position at every step as opposed to a desired trajectory. VelocityFollowingLoss: compute the loss to encourage tracking a target velocity. WaypointFollowingLoss: compute the loss to encourage tracking a target waypoint. AnimatedEMDLoss: compute the loss to track a sequence of moving point clouds with earth moving distance (EMD). RotationLoss: compute the loss to encourage rotation along a desired axis. ThrowingObjectLoss: compute the loss based on the average position of an object with respect to its starting position at the final step. ObjectVelocityLoss: compute the loss based on the average velocity of an object at every step.
> 
> Please check more detailed implement in [./algorithms/diffsim/loss.py](https://github.com/zswang666/softzoo/blob/main/algorithms/diffsim/loss.py)
> 
> actuator_v: velocity defined on actuators (muscle groups), where each actuator involves many particles in MPM. particle_v: velocity defined on MPM particles

Thx!
