### ISSUE TITLE
About using multiple environments in a program

### ISSUE THREAD

**Issue by Yuxing-Wang-THU** [zswang666/softzoo#4]
Hi! When I want to use multiple environments in my program, like the following code:
```python
TRAINENVS=["ground", "wetland", "ice", "shallow_water"]
for i in range(len(TRAINENVS)):
        ti.init(arch=ti.gpu,device_memory_fraction=0.8)
        individual_args={"env_config_file": f"{TRAINENVS[i]}.yaml",
                        "annotated_pcd_path": f"./softzoo/assets/meshes/pcd/panda.pcd"}
        for k, v in individual_args.items():
            setattr(args, k, v)
        env = make_env(args)

       # Doing some training under this env
```
When I finish a training round and start training in the next environment, I found that the memory of the program increases. Is there any way to free up memory occupied by a previous environment? Otherwise the computer's memory will overflow.

Thx!

**Comment by zhouxian** [comment]
try `ti.reset()`?

**Comment by Yuxing-Wang-THU** [comment]
> try `ti.reset()`?

thx! I will try
